name: "Build and push to ghcr.io"
description: >
  This composite action builds a Docker image, tags it with the current git
  branch/tag ref, and pushes it to ghcr.io.
inputs:
  github_token:
    description: "The GitHub token to use for authentication."
    required: true
  image:
    description: "The name of the Docker image to build."
    required: true
  dockerfile:
    description: "The name of the Dockerfile to build."
    required: false
    default: "Dockerfile"
  context:
    description: "The build context to use."
    required: false
    default: "."
  push:
    description: "Whether to push the image to ghcr.io."
    required: false
    default: "true"
  platforms:
    description: "List of target platforms for build"
    required: false
  target:
    description: "Name of target stage to build"
    required: false
  build-args:
    description: "List of build-time variables"
    required: false
  additional-tags:
    description: "List of additional tags to add to built image"
    required: false
outputs:
  tag:
    description: "The tag of the Docker image that was built."
    value: ${{ steps.tag.outputs.tag }}
  fully_qualified_image_digest:
    description: "A complete, unique, immutable identifier for the built image, including the registry and digest"
    value: "ghcr.io/${{ inputs.image }}@${{ steps.build.outputs.digest }}"

runs:
  using: "composite"
  steps:

    - name: Define the tag
      id: tag
      shell: bash
      run: echo "tag=`bash ${{ github.action_path  }}/docker-tag.sh`" >> ${GITHUB_OUTPUT}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ inputs.image }}
        tags: |
          type=raw,${{ steps.tag.outputs.tag }}
          ${{ inputs.additional-tags }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      if: fromJSON(inputs.push) == true
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: "${{ inputs.context }}"
        file: "${{ inputs.dockerfile }}"
        build-args: "${{ inputs.build-args }}"
        target: "${{ inputs.target }}"
        push: ${{ fromJSON(inputs.push) == true }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
